name: mindalae
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter 
  url_launcher: ^6.0.3
  audioplayers: ^6.4.0
  chewie: ^1.3.0
  video_player: ^2.8.1
  volume_controller: ^2.0.4
  youtube_player_flutter: 9.1.1
  youtube_api: ^1.0.0         
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.0
 


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#FFFFFF" # fondo oscuro o el que prefieras
  image: assets/logo4.png
  android: true
  ios: false
  android_gravity: center
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo3.jpg"
    

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png
    - assets/logo2.png
    - assets/logo3.jpg
    - assets/logo4.png
    


