name: mindalae
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter 
  url_launcher: ^6.0.3
  audioplayers: ^6.4.0
  chewie: ^1.3.0
  video_player: ^2.8.1
  volume_controller: ^2.0.4
  youtube_player_flutter: ^9.0.4
  youtube_api: ^1.0.0         
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0 # si quieres autenticación
  cloud_firestore: ^4.15.8 # si vas a usar base de datos
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7
  intl: ^0.18.0
  


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#000000"
  image: assets/logo4.png
  android: true
  ios: false
  android_gravity: center
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  ndroid_adaptive_icon_background: "#FF000000"
  image_path: "assets/logo4.png"
    

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png
    - assets/logo2.png
    - assets/logo3.jpg
    - assets/logo4.png
    - assets/mindalaev.mp4
    - assets/google_logo.png
    


